### ISSUE TITLE
Add additional features from VEP

### ISSUE THREAD

**Issue by arvkevi** [arvkevi/clinvar-kaggle#1]
An easy enhancement to the dataset would be to add additional features from VEP annotations.

[Link to VEP annotations on the ClinVar .vcf](http://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Results?db=core;tl=8rkfEtR0VSlohVzd-4099217)

I'm trying to get annotations with one consequence per variant (e.g. one transcript/variant). It will be easier to parse the `CSQ` field.  But at first glance, it doesn't appear to be performing how I expect. Maybe @CarlosBorroto you've run into this before?

**Comment by CarlosBorroto** [comment]
Hi @arvkevi, VEP has many options to "pick" which transcript to generate annotations for. There isn't a right answer to which transcript you should pick. One option is to select the transcript with the worst consequence, but that will over estimate many variants impact by selecting transcripts that might be very rare or not even real.

In the past I chose to always keep all annotations, and decide on how to choose one downstream. It is possible we don't need that here. How are you parsing the `CSQ` field? PyVCF makes parsing VCF files very easy.

Look for section `Filtering and QC options` to find out about available transcript/annotation selection:
https://useast.ensembl.org/info/docs/tools/vep/script/vep_options.html
