### ISSUE TITLE
Data Description

### ISSUE THREAD

**Issue by Meaad96s** [arvkevi/clinvar-kaggle#2]
Can I know the features description since most of it abbreviations? what does it refer to, if there is a link of the data description please share it

**Comment by arvkevi** [comment]
Thanks @Meaad96s I've updated the features a bit in Kaggle. There is also a good bit of information [here](https://www.ncbi.nlm.nih.gov/variation/docs/ClinVar_vcf_files/). But it looks many columns have changed in the past year and these are now outdated. At the moment, I won't be able to keep the Kaggle dataset updated with the most recent ClinVar dataset.

**Comment by Meaad96s** [comment]
thanks
