### ISSUE TITLE
License File Missing

### ISSUE THREAD

**Issue by rulaszek** [arvkevi/clinvar-kaggle#3]
Hello Kevin,

My name is Ryan Ulaszek and I work at Amazon as a Solution Architect in Life Sciences. Would you be willing to add a license file to the repo? It looks like the Kaggle project is under Create Commons but this repo doesn't have the Creative Commons license file. We think the work you have done is a great example of machine learning in genomics and would like to build an AWS Solution based on it. We will of course point back to your GitHub repo and Kaggle site to give you credit. We would like to use your dataset and the process_clinvar.py file.

Thanks,

Ryan

**Comment by arvkevi** [comment]
Hello Ryan,
Does the license need to be CC for your team to use the repo, or if I use MIT will that still be OK for you to use?

I haven't checked in on this repository in some time, so I don't know if everything will work "out-of-the-box". For example, I think ClinVar may have updated their file format. Additionally, as several Kaggle users have pointed out, this dataset could also be converted into either a multiclass or even a multilabel classification task. I'd be happy to hack on this a bit if things progress.

Thank you,
Kevin

**Comment by rulaszek** [comment]
MIT is great. That you very much for adding the license file. 

The MIT license would need to match this link: https://spdx.org/licenses/MIT.html

Or one of these variants:

http://spdx.org/licenses/ISC.html
http://spdx.org/licenses/X11.html
https://www.bouncycastle.org/licence.html
http://spdx.org/licenses/BSL-1.0.html
https://spdx.org/licenses/PostgreSQL.html

Let me check with the ML person I'm working with to see if it makes sense to make changes. I appreciate you offering.  I'll get back to you after I speak with him.

Thanks again for adding the license.

Ryan

**Comment by arvkevi** [comment]
Great, I added, the MIT license in #4
