### ISSUE TITLE
Vawk and Gawk dependencies

### ISSUE THREAD

**Issue by rulaszek** [arvkevi/clinvar-kaggle#5]
Hello Kevin,

Is there an easy way to break the dependency on Vawk and Gawk?  We can easily add zips of python packages to Glue jobs but binaries are a challenge and Gawk is a binary.  Can you think of an easy way to rework the process_clinvar.py script with only python dependencies?

Thanks,

Ryan

**Comment by arvkevi** [comment]
Hi Ryan,
Yes, I have a local branch that just parses the file with pandas. I will work on getting a working version pushed.

**Comment by rulaszek** [comment]
Awesome, that would help a lot. Thanks.

**Comment by arvkevi** [comment]
Check out the branch [here](https://github.com/arvkevi/clinvar-kaggle/tree/remove_vawk_dependency).

It should get you started. But I can't get it to run on new versions of ClinVar, I think because I am merging large DataFrame and running out of RAM. I'm working on a better solution now (sorry I was unavailable last week, but eager to hack this week).

**Comment by nihirc** [comment]
Hi Kevin,

I am making use of your code that parses the file with pandas, however, I am running into an issue on line 81. 

`csq_df[cols] = csq_df['CSQ'].str.split('|').apply(pd.Series)`

It fails with error - ValueError: Columns must be same length as key

I am using sample clinvar files from your repository.

**Comment by arvkevi** [comment]
Hi @nihirc I'm rewriting the script to be more a more performant solution, should be done today.

**Comment by arvkevi** [comment]
@rulaszek @nihirc can you please check out the update to the [`remove_vawk_dependency`](https://github.com/arvkevi/clinvar-kaggle/tree/remove_vawk_dependency) branch?
If it works for you, I will merge it then update the dataset version on Kaggle.

Thanks!

**Comment by nihirc** [comment]
@arvkevi I tested out new updates and it works great!. Thanks for the quick updates and I really like not having dependencies on vawk/gawk.

**Comment by arvkevi** [comment]
Great, @rulaszek let me know if you think we can close the issue.

Please note, I have updated the version on [Kaggle](https://www.kaggle.com/kevinarvai/clinvar-conflicting).

**Comment by rulaszek** [comment]
I think we’re good now. Thank you for making these changes, we really appreciate it. You can close the ticket.

**Comment by rulaszek** [comment]
Hello Kevin, 

We are getting close to launching the AWS Solution based on your Kaggle project and we would appreciate your input. Can you email me at rulaszek@amazon.com so we can discuss this further?

Thanks,

Ryan
